#!/usr/bin/env bash

set -euo pipefail

git rev-parse --is-inside-work-tree >/dev/null 2>&1 || exit 1

branches=$(git for-each-ref \
    --format='%(refname:short)' \
    refs/heads)

selected=$(printf "%s\n" $branches \
    | fzf --height=40% --reverse --border \
        --prompt="Select branch : ")

[ -z "$selected" ] && exit 0

git switch "$selected"
